version: '2'
services:
  mongo_db:
    image: mongo:3.4.3
    restart: always
    ports:
      - 27017:27017 

  node_js:
    container_name: aspect_node_js_srv
    image: aspect_node/wrapper:2017.04.12
    restart: always
    ports:
      - 80:3800
    links:
      - mongo_db
    extra_hosts:
      - "mongodbhost:1.2.3.4"
