version: '3.1'

services:

  mysql:
    image: mariadb:10.1
    container_name: mysql
    volumes:
      - ./var/mysql/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Gaming2017
      - MYSQL_DATABASE=gogs
      - MYSQL_USER=gogs
      - MYSQL_PASSWORD=Gaming2017
    command :
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    restart: always

  gogs:
    container_name: gogs
    image: gogs/gogs:0.11.4
    restart: always
    depends_on:
      - mysql
    ports:
      - "10022:22"
      - "10080:3000"
    volumes:
      - ./var/gogs:/data
